---
title: "Supplement 1"
subtitle: "Primary outcome: frequency of pain"
author: "Peter Kamerman"
date: "Last knitted: `r format(Sys.Date(), '%d %B %Y')`"
---

```{r setup, include = FALSE}
# Load packages
library(magrittr)
library(tidyverse)
library(skimr)

# skimr options
skim_with(numeric = list(hist = NULL),
          factor = list(ordered = NULL))

# ggplot theme
theme_set(new = theme_bw(base_size = 16))

# Palette
pal <- c('#0072B2', '#D55E00')

# Knitr options
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)
```

----

This script addresses the primary outcome of the study, namely, whether the frequency of pain is greater in a group of individuals infected with HIV than a group that is not infected. Our _a priori_ hypothesis was directional and specified that HIV infection was associated with an increase in pain frequency. Consequently we conducted a one-tailed independence test assessing whether infection by the HIV was associated with greater frequency of pain. 

----

# Inspect data

```{r import_data, include = FALSE}
# Import test result data and select columns
test <- read_rds('data-cleaned/hiv_test_results.rds') %>% 
    select(PID,
           test_result) %>% 
    rename(HIV_positive = test_result) %>% 
    mutate(HIV_positive = ifelse(HIV_positive == 'HIV positive',
                                 yes = 'yes',
                                 no = 'no'))
    

# Import pain data and select columns
pain <- read_rds('data-cleaned/wbpq.rds') %>% 
    select(PID,
           pain_in_last_month) %>% 
    set_colnames(c('PID', 'pain'))

# Join datasets 
data <- pain %>% 
    left_join(test)
```

#### Data structure

```{r inspect_structure}
dim(data)
head(data)
tail(data)
glimpse(data)
```

#### Data summaries

```{r inspect_summaries}
# Convert character to factor
data_fct <- data %>% 
    mutate(HIV_positive = factor(HIV_positive),
           pain = factor(pain)) %>% 
    select(-PID)

# Full cohort
data_fct %>%
    skim()

# By HIV status
data_fct %>% 
    group_by(pain) %>% 
    skim()
```

----

# Clean data

#### Remove incomplete cases

Five (5) individuals missing test result data.

```{r clean}
data %<>%
    filter(complete.cases(.)) 
```

----

# Analyse primary outcome

#### Exploratory plot

```{r plots}
# Prepare data 
plot_data <- data %>% 
    group_by(HIV_positive, pain) %>% 
    summarise(count = n()) %>% 
    mutate(prop = round(count/sum(count) * 100, 1)) %>% 
    ungroup()

# Count plot
ggplot(data = plot_data) +
    aes(x = HIV_positive,
        y = count,
        fill = pain,
        colour = pain) +
    geom_col(position = position_fill()) +
    geom_label(aes(label = paste0('n = ', count)), 
               position = position_fill(vjust = 0.5), 
               colour = 'white', 
               show.legend = FALSE) +
    labs(title = 'Pain prevalence: counts',
         y = 'Count',
         x = 'HIV positive') + 
    scale_fill_manual(name = 'Pain in the\nlast month',
                      values = pal) +
    scale_colour_manual(name = 'Pain in the\nlast month',
                        values = pal)

# Proportion plot
ggplot(data = plot_data) +
    aes(x = HIV_positive,
        y = prop,
        fill = pain,
        colour = pain) +
    geom_col(position = position_fill()) +
    geom_label(aes(label = paste0(prop, '%')),
               position = position_fill(vjust = 0.5),
               colour = 'white', 
               show.legend = FALSE) +
    labs(title = 'Pain prevalence: proportions',
         y = 'Proportion',
         x = 'HIV positive') + 
    scale_fill_manual(name = 'Pain in the\nlast month',
                      values = pal) +
    scale_colour_manual(name = 'Pain in the\nlast month',
                        values = pal)
```

#### Statistical inference

```{r pain_inference}
# Tabulate data
(table_stats <- xtabs(~ pain + HIV_positive,
                     data = data))

# Fisher's exact test
fisher.test(table_stats,
            alternative = 'greater')
```
